# Generated by Django 5.0.4 on 2024-04-30 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fath', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='fath.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='filter_choice',
            field=models.CharField(choices=[('po', 'Popularity'), ('org', 'Organic'), ('fan', 'Fantastic')], max_length=255, null=True),
        ),
    ]
